name: simple_manga_translation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^4.5.1
  bitsdojo_window: ^0.1.1
  dio: ^4.0.6
  flutter_svg: ^1.0.3
  rxdart: ^0.27.3
  desktop_window: ^0.4.0
  mime: ^1.0.2
  localstore: ^1.2.3
  equatable: ^2.0.3
  uuid: ^3.0.0
  http: ^0.13.4
  drift: ^1.6.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.5
  rx_shared_preferences: ^2.3.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path: ^1.8.1
  url_launcher: ^6.1.2
  package_info_plus: ^1.4.2
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.3


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
